UNET_LAYERS = ['IN01', 'IN02', 'IN04', 'IN05', 'IN07', 'IN08', 'MID',
               'OUT03', 'OUT04', 'OUT05', 'OUT06', 'OUT07', 'OUT08', 'OUT09', 'OUT10', 'OUT11']

SD_INFERENCE_TIMESTEPS = [999, 979, 959, 939, 919, 899, 879, 859, 839, 819, 799, 779, 759, 739, 719, 699, 679, 659,
                          639, 619, 599, 579, 559, 539, 519, 500, 480, 460, 440, 420, 400, 380, 360, 340, 320, 300,
                          280, 260, 240, 220, 200, 180, 160, 140, 120, 100, 80, 60, 40, 20]

# PROMPTS = [
#     "A photo of {} in the jungle",
#     "A photo of {} on a beach",
#     "A photo of {} in Times Square",
#     "A photo of {} in the moon",
#     "A painting of {} in the style of Monet",
#     "Oil painting of {}",
#     "A Marc Chagall painting of {}",
#     "A manga drawing of {}",
#     'A watercolor painting of {}',
#     "A statue of {}",
#     "App icon of {}",
#     "A sand sculpture of {}",
#     "Colorful graffiti of {}",
#     "{} wearing a Santa hat",
#     "{} in a construction outfit",
#     "{} on the cover of Time magazine",
#     "A movie poster of {}",
#     "{} is wearing a doctoral gown and a doctoral cap",
#     "{} in an astronaut suit",
#     "A photo of {} wearing a life jacket",
#     "{} as a jedi master, inside hogwarts with a mystical scepter",
#     "{} wearing a sombrero",
#     "{} dressed like a wizard, reading a grimoire",
#     "{} as a character in the Sherlock Holmes' movie",
#     "{} buckled in a seat on a plane",
#     "A selfie of {} in Times Square",
#     "An oil painting of {}",
#     "A photo of {} as a cowboy",
#     "{} in a chef's outfit, cooking in a kitchen",
#     "{} selfie standing under the pink blossoms of a cherry tree",
# ]

PROMPTS = [
    "A {} is giving a speech on the podium", 
    "A {} is walking on the red carpet at the evening gala",
    "A {} is holding a Halloween pumpkin lantern",
    "A {} is reading a book",
    "A {} wearing winter camo military gear in the snow",
    "A {} sitting in a hammock",
    "A photo of {} as an knight in armor",
    "A {} as a police officer",
    "A photo of {} in the lab",
    "A {} sitting a leather sofa",
    "A {} is reading newspaper, sitting in a busy train",
    "A {} in a jungle",
    "A {} is playing the piano",
    "A {} is doing a skateboard",
    "A {} is riding a motorcycle, road background",
    "{} is working on a beautiful design project, creating design projects, in a beautiful workspace",
    "{} driving a racing car",
    "{} floats on a raft along the street of a flooded city",
    "{} baking pizza in front of a wood-fired oven",
    "{} plays bass guitar on stage",
]

VALIDATION_PROMPTS = [
    "A photo of a {}",
    "A photo of a {} on a beach",
    "App icon of {}",
    "A painting of {} in the style of Monet",
]

IMAGENET_TEMPLATES_SMALL = [
    "a photo of a {}",
    "a rendering of a {}",
    "a cropped photo of the {}",
    "the photo of a {}",
    "a photo of a clean {}",
    "a photo of a dirty {}",
    "a dark photo of the {}",
    "a photo of my {}",
    "a photo of the cool {}",
    "a close-up photo of a {}",
    "a bright photo of the {}",
    "a cropped photo of a {}",
    "a photo of the {}",
    "a good photo of the {}",
    "a photo of one {}",
    "a close-up photo of the {}",
    "a rendition of the {}",
    "a photo of the clean {}",
    "a rendition of a {}",
    "a photo of a nice {}",
    "a good photo of a {}",
    "a photo of the nice {}",
    "a photo of the small {}",
    "a photo of the weird {}",
    "a photo of the large {}",
    "a photo of a cool {}",
    "a photo of a small {}",
]

IMAGENET_STYLE_TEMPLATES_SMALL = [
    "a painting in the style of {}",
    "a rendering in the style of {}",
    "a cropped painting in the style of {}",
    "the painting in the style of {}",
    "a clean painting in the style of {}",
    "a dirty painting in the style of {}",
    "a dark painting in the style of {}",
    "a picture in the style of {}",
    "a cool painting in the style of {}",
    "a close-up painting in the style of {}",
    "a bright painting in the style of {}",
    "a cropped painting in the style of {}",
    "a good painting in the style of {}",
    "a close-up painting in the style of {}",
    "a rendition in the style of {}",
    "a nice painting in the style of {}",
    "a small painting in the style of {}",
    "a weird painting in the style of {}",
    "a large painting in the style of {}",
]
